@ECHO OFF
REM   IF    EXIST DEMO.EXE GOTO B
REM   AUTOEXEC.BAT:
REM   SET OBJ=E:\CLIP
REM   SET LIB=E:\CLIP
REM   SET CLIPPER=V40;F30;R0
REM   PATH E:\CLIP;
CLS
CLIPPER DEMO
IF NOT  ERRORLEVEL 1 GOTO A
EXIT
 :A
REM PLINK86 FI DEMO,PEREKOD   LIB CLIPPER,EXTEND
    LINK510 DEMO+PEREKOD,,NUL,CLIPPER+EXTEND,NUL /SE:400
DEL DEMO.OBJ
 :B
IF NOT  ERRORLEVEL 1 DEMO.EXE
