#----------------------------------------------------------------------------
#   Dialog data and code block - do not modify this code by hand
#   Generated by LIBERO 2.11 on 17 May, 1996,  7:35.
#   Schema file used: lrschema.pl
#----------------------------------------------------------------------------

#-- Symbolic constants and event numbers ------------------------------------

$LR_defaults_state = 6;
$LR_STATE_after_init = 0;
$LR_STATE_collect_titles = 1;
$LR_STATE_skip_block = 2;
$LR_STATE_before_page = 3;
$LR_STATE_inside_page = 4;
$LR_STATE_collect_block = 5;
$LR_STATE_defaults = 6;

$terminate_event = -1;                  # Halts the dialog
$LR_NULL_EVENT = -2;
$blank_line_event = 0;
$block_event = 1;
$body_text_event = 2;
$build_event = 3;
$comment_event = 4;
$continue_event = 5;
$define_event = 6;
$echo_event = 7;
$else_event = 8;
$end_event = 9;
$endif_event = 10;
$error_event = 11;
$exception_event = 12;
$finished_event = 13;
$if_event = 14;
$ignore_event = 15;
$ignore_pages_event = 16;
$include_event = 17;
$ok_event = 18;
$page_event = 19;
$return_event = 20;

#-- Standard subroutines used by dialog interpreter -------------------------

sub raise_exception {
    local ($event) = @_;
    $the_exception_event = $event;
    $exception_raised = 1;
}

sub LR_initialise {
    $LR_nextst = "";
    $LR_nextst .= "000000000000000000100";
    $LR_nextst .= "121111111111031111010";
    $LR_nextst .= "222221222122022222020";
    $LR_nextst .= "353333333333033333043";
    $LR_nextst .= "454444444444044444044";
    $LR_nextst .= "555555555555055555045";
    $LR_nextst .= "000000000000600000000";

    $LR_action = "";
    $LR_action .= "000000000000000000000002000000000000010000";
    $LR_action .= "040403040404050411040404001210070906000800";
    $LR_action .= "040404130404130411040404001310130913001300";
    $LR_action .= "041614180404052011171904002110070906001504";
    $LR_action .= "231622250404052011171904002610070906002404";
    $LR_action .= "272827180429052011291904002110070906001504";
    $LR_action .= "000000000000000000000000020000000000000000";

    $LR_module = "";
    $LR_module .= "1718281915" . "00";
    $LR_module .= "37" . "00";
    $LR_module .= "140915" . "00";
    $LR_module .= "15" . "00";
    $LR_module .= "143515" . "00";
    $LR_module .= "14362115" . "00";
    $LR_module .= "141615" . "00";
    $LR_module .= "14040815" . "00";
    $LR_module .= "2415" . "00";
    $LR_module .= "143415" . "00";
    $LR_module .= "3315" . "00";
    $LR_module .= "07321915" . "00";
    $LR_module .= "3037" . "00";
    $LR_module .= "2615" . "00";
    $LR_module .= "1404202315" . "00";
    $LR_module .= "051511" . "00";
    $LR_module .= "3115" . "00";
    $LR_module .= "2715" . "00";
    $LR_module .= "0615" . "00";
    $LR_module .= "141315" . "00";
    $LR_module .= "07292537" . "00";
    $LR_module .= "14021015" . "00";
    $LR_module .= "1015" . "00";
    $LR_module .= "042214202315" . "00";
    $LR_module .= "0315" . "00";
    $LR_module .= "0722292537" . "00";
    $LR_module .= "0115" . "00";
    $LR_module .= "0515" . "00";
    $LR_module .= "12" . "00";

    @LR_offset [1] = 0;
    @LR_offset [2] = 6;
    @LR_offset [3] = 8;
    @LR_offset [4] = 12;
    @LR_offset [5] = 14;
    @LR_offset [6] = 18;
    @LR_offset [7] = 23;
    @LR_offset [8] = 27;
    @LR_offset [9] = 32;
    @LR_offset [10] = 35;
    @LR_offset [11] = 39;
    @LR_offset [12] = 42;
    @LR_offset [13] = 47;
    @LR_offset [14] = 50;
    @LR_offset [15] = 53;
    @LR_offset [16] = 59;
    @LR_offset [17] = 63;
    @LR_offset [18] = 66;
    @LR_offset [19] = 69;
    @LR_offset [20] = 72;
    @LR_offset [21] = 76;
    @LR_offset [22] = 81;
    @LR_offset [23] = 86;
    @LR_offset [24] = 89;
    @LR_offset [25] = 96;
    @LR_offset [26] = 99;
    @LR_offset [27] = 105;
    @LR_offset [28] = 108;
    @LR_offset [29] = 111;
}

sub dialog_call
{
    $LR_stack_size < 20 || die
        "State ", $LR_state, " - Dialog-Call overflow\n";
    @LR_stack [++$LR_stack_size] = $LR_state;
}

sub dialog_return
{
    $LR_stack_size > 0 || die
        "State ", $LR_state, " - Dialog-Return underflow\n";
    $LR_state = @LR_stack [$LR_stack_size--];
    &raise_exception ($return_event);
}

#-- Dialog interpreter starts here ------------------------------------------

$LR_state = 0;                          #   First state is always 0
$LR_stack_size = 0;                     #   Clear subdialog stack
&LR_initialise;                         #   Initialise static strings
&initialise_the_program;
while ($the_next_event != $terminate_event)
  {
    $LR_event = $the_next_event;
    $LR_event < 0 || $LR_event >= 21 && die
        "State ", $LR_state,
        " - event ", $LR_event, " is out of range\n";
    $LR_index = ($LR_state * 21 + $LR_event) * 2;
    $LR_index = substr ($LR_action, $LR_index, 2);
    $LR_savest = $LR_state;

    #   If no action for this event, try the defaults state
    if ($LR_index == 0)
      {
        $LR_state = $LR_defaults_state;
        $LR_index = ($LR_state * 21 + $LR_event) * 2;
        $LR_index = substr ($LR_action, $LR_index, 2);
        $LR_index == 0 && die
            "State ", $LR_state,
            " - event ", $LR_event, " is not accepted\n";
      }
    $the_next_event = $LR_NULL_EVENT;
    $the_exception_event = $LR_NULL_EVENT;
    $exception_raised = 0;

    #   Execute module list for state transition, 0 indicates end of list
    $LR_vecptr = @LR_offset [$LR_index];
    $LR_modnbr = substr ($LR_module, $LR_vecptr * 2, 2);
    while ($LR_modnbr > 0 && !$exception_raised)
      {
        EXECUTE:                        #   Execute the module
          {
            $LR_modnbr == 1 && do { &add_line_to_block; last EXECUTE; };
            $LR_modnbr == 2 && do { &anchor_title_if_present; last EXECUTE; };
            $LR_modnbr == 3 && do { &build_specified_table; last EXECUTE; };
            $LR_modnbr == 4 && do { &check_if_ignore_pages; last EXECUTE; };
            $LR_modnbr == 5 && do { &clear_specified_block; last EXECUTE; };
            $LR_modnbr == 6 && do { &close_if_block_if_open; last EXECUTE; };
            $LR_modnbr == 7 && do { &close_the_document; last EXECUTE; };
            $LR_modnbr == 8 && do { &collect_page_information; last EXECUTE; };
            $LR_modnbr == 9 && do { &collect_title_if_present; last EXECUTE; };
            $LR_modnbr == 10 && do { &copy_line_to_output_page; last EXECUTE; };
            $LR_modnbr == 11 && do { &dialog_call; last EXECUTE; };
            $LR_modnbr == 12 && do { &dialog_return; last EXECUTE; };
            $LR_modnbr == 13 && do { &echo_text_to_console; last EXECUTE; };
            $LR_modnbr == 14 && do { &expand_symbols_in_line; last EXECUTE; };
            $LR_modnbr == 15 && do { &get_next_document_line; last EXECUTE; };
            $LR_modnbr == 16 && do { &handle_ignore_command; last EXECUTE; };
            $LR_modnbr == 17 && do { &initialise_program_data; last EXECUTE; };
            $LR_modnbr == 18 && do { &load_anchor_definitions; last EXECUTE; };
            $LR_modnbr == 19 && do { &open_main_document; last EXECUTE; };
            $LR_modnbr == 20 && do { &open_new_output_page; last EXECUTE; };
            $LR_modnbr == 21 && do { &open_the_document; last EXECUTE; };
            $LR_modnbr == 22 && do { &output_footer_for_page; last EXECUTE; };
            $LR_modnbr == 23 && do { &output_header_for_page; last EXECUTE; };
            $LR_modnbr == 24 && do { &parse_page_title_only; last EXECUTE; };
            $LR_modnbr == 25 && do { &save_anchor_definitions; last EXECUTE; };
            $LR_modnbr == 26 && do { &signal_body_text_skipped; last EXECUTE; };
            $LR_modnbr == 27 && do { &signal_build_not_expected; last EXECUTE; };
            $LR_modnbr == 28 && do { &signal_collecting_titles; last EXECUTE; };
            $LR_modnbr == 29 && do { &signal_document_processed; last EXECUTE; };
            $LR_modnbr == 30 && do { &signal_end_block_missing; last EXECUTE; };
            $LR_modnbr == 31 && do { &signal_end_not_expected; last EXECUTE; };
            $LR_modnbr == 32 && do { &signal_formatting_pages; last EXECUTE; };
            $LR_modnbr == 33 && do { &skip_else_block_always; last EXECUTE; };
            $LR_modnbr == 34 && do { &skip_if_block_if_false; last EXECUTE; };
            $LR_modnbr == 35 && do { &store_symbol_definition; last EXECUTE; };
            $LR_modnbr == 36 && do { &take_include_file_name; last EXECUTE; };
            $LR_modnbr == 37 && do { &terminate_the_program; last EXECUTE; };
          }
        $LR_vecptr++;
        $LR_modnbr = substr ($LR_module, $LR_vecptr * 2, 2);
      }

    #   Handle exception if any was raised
    if ($exception_raised)
      {
        $the_exception_event == $LR_NULL_EVENT ||
            ($LR_event = $the_exception_event);

        $the_next_event = $LR_event;
      }
    else
      {
        $LR_index = ($LR_state * 21 + $LR_event) * 1;
        $LR_state = substr ($LR_nextst, $LR_index, 1);
      }
    $LR_state = $LR_savest if ($LR_state == $LR_defaults_state);
    if ($the_next_event == $LR_NULL_EVENT)
      {
        &get_external_event;
        $the_next_event == $LR_NULL_EVENT && die
            "No event set after event ", $LR_event,
            " in state ", $LR_state, "\n";
      }
  }
1;                                      #   Return true value
