		CtrlBreak	 = #$00; { 0,Scan = $00}
		AltESC		 = #$01; { 1,Scan = $00}
		AltFire		 = #$05; { 5,Scan = $00}
		AltBS		 = #$0E; { 14,Scan = $00}
		ShiftTab	 = #$0F; { 15,Scan = $00}

                AltQ             = #$10; { 16,Scan = $00}
		AltW		 = #$11; { 17,Scan = $00}
		AltE		 = #$12; { 18,Scan = $00}
		AltR		 = #$13; { 19,Scan = $00}
		AltT		 = #$14; { 20,Scan = $00}
		AltY		 = #$15; { 21,Scan = $00}
		AltU		 = #$16; { 22,Scan = $00}
		AltI		 = #$17; { 23,Scan = $00}
		AltO		 = #$18; { 24,Scan = $00}
		AltP		 = #$19; { 25,Scan = $00}
		AltEnter	 = #$1C; { 28,Scan = $00}
		AltA		 = #$1E; { 30,Scan = $00}
		AltS		 = #$1F; { 31,Scan = $00}
		AltD		 = #$20; { 32,Scan = $00}
		AltF		 = #$21; { 33,Scan = $00}
		AltG		 = #$22; { 34,Scan = $00}
		AltH		 = #$23; { 35,Scan = $00}
		AltJ		 = #$24; { 36,Scan = $00}
		AltK		 = #$25; { 37,Scan = $00}
		AltL		 = #$26; { 38,Scan = $00}
		AltQuite	 = #$29; { 41,Scan = $00}
		AltSlash	 = #$2B; { 43,Scan = $00}
		AltZ		 = #$2C; { 44,Scan = $00}
		AltX		 = #$2D; { 45,Scan = $00}
		AltC		 = #$2E; { 46,Scan = $00}
		AltV		 = #$2F; { 47,Scan = $00}
		AltB		 = #$30; { 48,Scan = $00}
		AltN		 = #$31; { 49,Scan = $00}
		AltM		 = #$32; { 50,Scan = $00}

		F1		 = #$3B; { 59,Scan = $00}
		F2		 = #$3C; { 60,Scan = $00}
		F3		 = #$3D; { 61,Scan = $00}
		F4		 = #$3E; { 62,Scan = $00}
		F5		 = #$3F; { 63,Scan = $00}
		F6		 = #$40; { 64,Scan = $00}
		F7		 = #$41; { 65,Scan = $00}
		F8		 = #$42; { 66,Scan = $00}
		F9		 = #$43; { 67,Scan = $00}
		F10		 = #$44; { 68,Scan = $00}

		Home		 = #$47; { 71,Scan = $00}
		Up		 = #$48; { 72,Scan = $00}
		PgUp		 = #$49; { 73,Scan = $00}
		Left		 = #$4B; { 75,Scan = $00}
		Fire		 = #$4C; { 76,Scan = $00}
		Right		 = #$4D; { 77,Scan = $00}
		FEnd		 = #$4F; { 79,Scan = $00}
		Down		 = #$50; { 80,Scan = $00}
		PgDn		 = #$51; { 81,Scan = $00}
		Ins		 = #$52; { 82,Scan = $00}
		Del		 = #$53; { 83,Scan = $00}

		ShiftF1		 = #$54; { 84,Scan = $00}
		ShiftF2		 = #$55; { 85,Scan = $00}
		ShiftF3		 = #$56; { 86,Scan = $00}
		ShiftF4		 = #$57; { 87,Scan = $00}
		ShiftF5		 = #$58; { 88,Scan = $00}
		ShiftF6		 = #$59; { 89,Scan = $00}
		ShiftF7		 = #$5A; { 90,Scan = $00}
		ShiftF8		 = #$5B; { 91,Scan = $00}
		ShiftF9		 = #$5C; { 92,Scan = $00}
		ShiftF10	 = #$5D; { 93,Scan = $00}

		CtrlF1		 = #$5E; { 94,Scan = $00}
		CtrlF2		 = #$5F; { 95,Scan = $00}
		CtrlF3		 = #$60; { 96,Scan = $00}
		CtrlF4		 = #$61; { 97,Scan = $00}
		CtrlF5		 = #$62; { 98,Scan = $00}
		CtrlF6		 = #$63; { 99,Scan = $00}
		CtrlF7		 = #$64; { 100,Scan = $00}
		CtrlF8		 = #$65; { 101,Scan = $00}
		CtrlF9		 = #$66; { 102,Scan = $00}
		CtrlF10		 = #$67; { 103,Scan = $00}

		AltF1		 = #$68; { 104,Scan = $00}
		AltF2		 = #$69; { 105,Scan = $00}
		AltF3		 = #$6A; { 106,Scan = $00}
		AltF4		 = #$6B; { 107,Scan = $00}
		AltF5		 = #$6C; { 108,Scan = $00}
		AltF6		 = #$6D; { 109,Scan = $00}
		AltF7		 = #$6E; { 110,Scan = $00}
		AltF8		 = #$6F; { 111,Scan = $00}
		AltF9		 = #$70; { 112,Scan = $00}
		AltF10		 = #$71; { 113,Scan = $00}

		CtrlPrtScr	 = #$72; { 114,Scan = $00}

		CtrlLeft	 = #$73; { 115,Scan = $00}
		CtrlRight	 = #$74; { 116,Scan = $00}
		CtrlEnd		 = #$75; { 117,Scan = $00}
		CtrlPgDn	 = #$76; { 118,Scan = $00}
		CtrlHome	 = #$77; { 119,Scan = $00}

		Alt1		 = #$78; { 120,Scan = $00}
		Alt2		 = #$79; { 121,Scan = $00}
		Alt3		 = #$7A; { 122,Scan = $00}
		Alt4		 = #$7B; { 123,Scan = $00}
		Alt5		 = #$7C; { 124,Scan = $00}
		Alt6		 = #$7D; { 125,Scan = $00}
		Alt7		 = #$7E; { 126,Scan = $00}
		Alt8		 = #$7F; { 127,Scan = $00}
		Alt9		 = #$80; { 128,Scan = $00}
		Alt0		 = #$81; { 129,Scan = $00}
		AltMin		 = #$82; { 130,Scan = $00}
		AltPlus		 = #$83; { 131,Scan = $00}

		CtrlPgUp	 = #$84; { 132,Scan = $00}

		F11		 = #$85; { 133,Scan = $00}
		F12		 = #$86; { 134,Scan = $00}

		ShiftF11	 = #$87; { 135,Scan = $00}
		ShiftF12	 = #$88; { 136,Scan = $00}

		CtrlF11		 = #$89; { 137,Scan = $00}
		CtrlF12		 = #$8A; { 138,Scan = $00}

		AltF11		 = #$8B; { 139,Scan = $00}
		AltF12		 = #$8C; { 140,Scan = $00}

		CtrlFire	 = #$8F; { 143,Scan = $00}
		CtrlTab		 = #$94; { 148,Scan = $00}
		AltHome		 = #$97; { 151,Scan = $00}
		AltUp		 = #$98; { 152,Scan = $00}
		AltPgUp		 = #$99; { 153,Scan = $00}
		AltLeft		 = #$9B; { 155,Scan = $00}
		AltRight	 = #$9D; { 157,Scan = $00}
		AltEnd		 = #$9F; { 159,Scan = $00}
		AltDown		 = #$A0; { 160,Scan = $00}
		AltPgDn		 = #$A1; { 161,Scan = $00}
		AltInsert	 = #$A2; { 162,Scan = $00}
		AltDelete	 = #$A3; { 163,Scan = $00}
		AltTab		 = #$A5; { 165,Scan = $00}


		Tab		 = #$09; { 9,Scan = $0F}
		BackSpace	 = #$08; { 8,Scan = $0E}
		CtrlEnter	 = #$0A; { 10,Scan = $1C}
		Enter		 = #$0D; { 13,Scan = $1C}
		ESC		 = #$1B; { 27,Scan = $01}
		Space		 = #$20; { 32,Scan = $39}
		GreyPlus	 = #$2B; { 43,Scan = $4E}
		Min		 = #$2D; { 45,Scan = $0C}
		GreyMin		 = #$2D; { 45,Scan = $4A}
		Plus		 = #$3D; { 61,Scan = $0D}
		CtrlBS		 = #$7F; { 127,Scan = $0E}
