CC	= gcc
CFLAGS	= -O
OBJS1	= filelist.o dosdir.o match.o fnsplit.o
OBJS2	= example2.o dosdir.o match.o
OBJS3	= example3.o dirent.o

all: filelist example2 example3

filelist: $(OBJS1)
	$(CC) $(OBJS1) -o $@

example2: $(OBJS2)
	$(CC) $(OBJS2) -o $@

example3: $(OBJS3)
	$(CC) $(OBJS3) -o $@

.c.o:
	$(CC) -c $(CFLAGS) $<
