CC      = bcc
DEFINES = -DDOSWILD
CFLAGS  = $(DEFINES) -Z -O -w-par
OBJS    = filelist.obj match.obj dosdir.obj fnsplit.obj
OBJS2   = example2.obj dosdir.obj
OBJS3   = example3.obj dirent.obj

all: filelist.exe example2.exe example3.exe

filelist.exe: $(OBJS)
	$(CC) $(OBJS)

example2.exe: $(OBJS2)
	$(CC) $(OBJS2)

example3.exe: $(OBJS3)
	$(CC) $(OBJS3)

.c.obj:
	$(CC) -c $(CFLAGS) $<
