.TH DF 1 "10/14/94"
.SH NAME
df \- summarize disk usage
.SH SYNOPSIS
.B df
[
.B \-h
]
[
.B \-v
]
[
.B \-l
]
[
.B \-i
]
.SH DESCRIPTION
.I Df
gives a summary of disk usage on ms-dos system.
Special care was taken to specify joined drives, and not
abort on the floppy disk driver when a floppy disk is not
present.
.LP 
Specifying no options will show the format of your hard disk
when you use join (which I do). 
Each hard disk can have 1 main paritition and 1 extended partition,
which can be 4 dos disks.  
So you can have a total of 5 dos drives on each hard disk.
I use join, it can be confusing.
Don\'t believe the sizes about removable media, it isn't
always right and I didn't try to understand DOS's strategy for this.
.LP
On my hard disk, using 
.I df
with no options gives:
.nf
.ft CW
.in +3n
.ec !
Drive    Free K     Total K   %Free    Mount
A:                                     C:\A           
B:                                                    
C:        2922      103492    2                       
D:        16970     51264     33       C:\D           
E:        4564      24686     18       C:\TRY         
F:        5712      36842     15       C:\MARTY       
G:        3618      33908     10       C:\WINDOWS     
H:        5334      27200     19       C:\GNU         
I:        13522     40982     32       C:\QDECK       
J:        11392     20470     55       C:\TMP 
.ec
.fi
.ft
.in
Each join drive is the equivalent to a
.I "mount point"
in Unix.
.LP
Using the 
.I \-l
option shows the label 
.nf
.ft CW
.in +3n
.ec !
Drive    Free K     Total K   %Free    Mount         Label
A:                                     C:\A           
B:                                                    
C:        2922      103492    2                       WD DOS     
D:        16970     51264     33       C:\D           NO NAME    
E:        4564      24686     18       C:\TRY         TRY        
F:        5712      36842     15       C:\MARTY       MARTY      
G:        3618      33908     10       C:\WINDOWS     WINDOWS    
H:        5334      27200     19       C:\GNU         JUNK       
I:        13522     40982     32       C:\QDECK       QUARTERDECK
J:        11392     20470     55       C:\TMP         TMP        
.fi
.ft
.ec
.in
.LP
Specifying the 
.I \-i
option will show more information based on the settings for the flags
int the current directory structure.
It displays a combination of HAVE, REMOVABLE, JOINED and VALID.
Read the code to find out what this means.
.LP
Specifing the 
.I \-h
will
give help:
.nf
.in +3n
.ft CW
Usage:  [-e] [-l] [-v] [-i] [-s]
        -s      Status with function 32
        -i      Show drive information
        -v      Show version and quit
        -e      try to stat everything
        -l      display volume lables
.ft
.in
.fi
.LP
Specifing the \Fb-v\fP will give a version and date of compilation
and exit.
.SH LIMITATIONS
Just knows it works on DOS 6.2
.SH AUTHOR
.nf
Marty Leisner
leisner@sdsp.mc.xerox.com
.fi

