Return-Path: <helman@elm.sdd.trw.com>
Received: from elm.sdd.trw.com.sdd.trw.com by deneva.sdd.trw.com (4.1/SMI-4.0 TRW 1.8)
        id AA26924; Thu, 19 Sep 91 11:24:45 PDT
Received: by elm.sdd.trw.com.sdd.trw.com (4.1/SMI-4.1)
        id AA29761; Thu, 19 Sep 91 11:24:53 PDT
Date: Thu, 19 Sep 91 11:24:53 PDT
From: helman@elm.sdd.trw.com (Howard L. Helman)
Message-Id: <9109191824.AA29761@elm.sdd.trw.com.sdd.trw.com>
To: mdlawler@bsu-cs.edu
Subject: Source Update for SED
Cc: helman@elm.sdd.trw.com, kirsch@usasoc.soc.mil


Well guys here it is, the source and
documentation for my version of
sed.  I am also sending a compiled
version PC of course. 

The ASCII files which follow in
the zoo archive are in PC format
that is each line ends in \r\n


Happy seding

h**2

----------CUT HERE-------------------------------------------
begin 644 hhsed.zoo
[extracted]
