                        History of DIFF.C

    DIFF was developed by Kevin Kenny, when he was still here, on 
an 8-bit CP/M system using BDS C.  Later,  I converted the source 
to   16-bit   CP/M-86  using  the  CP/M-86  version  of  Computer 
Innovations C-86 C compiler.  Later yet, I converted it to MS-DOS 
generic using the MS-DOS version of CI C-86.  Stil later yet,  it 
was  used  as a test of portablility of C source by converting it 
to both Lattice and Mark Williams  C.  It  has  successfully  run 
under  all  conditions.  I  believe  that  Kevin  converted it to 
Waterloo C on GCOS just before he left but that source appears to 
be lost.  

    As you can see from his copyright statement,  Kevin developed 
this  program  in 1983,  if my memory serves me correctly,  early 
1983.  It has not been  functionally  modified  since  the  first 
release.  Kevin  did  release  the  source to the 'public domain' 
through the C-Users' Group (then the  BDS  C-Users'  Group.)  His 
intent,  as  he  informed  me,  in copyrighting the source was to 
discourage commercial use of his source  in  products  that  were 
later sold.  

    There  are  two  versions  of the main source program in this 
archive,  DIFF.BDS and DIFF.C.  DIFF.BDS is,  I believe,  Kevin's 
original source as released to th C-Users's Group.  DIFF.C is the 
converted  form for one of the 16-bit C compilers,  from the '.h' 
files, I would say Lattice C.  The DOC file is untouched by human 
hands since Kevin wrote it.  I do NOT  guarantee  that  the  .EXE 
file  was produced from the DIFF.C file,  it may well be the .EXE 
file produced by the Mark Williams compiler.  

    DIFF has not yet been converted to Aztec C (8-bit or 16-bit), 
DeSmet C, Microsoft C, MIX C, or any other 8- or 16-bit C.  


    Don-Willx4396

