        TITLE   SET_KB
ABS0    SEGMENT AT 0
        ORG   417H
STATUS  DW    ?
ABS0    ENDS
CSEG    SEGMENT PUBLIC 'CODE'
        ASSUME  CS:CSEG
	ORG	100H
START:
	XOR	AX,AX
	MOV	DS,AX
	MOV	DS:STATUS,40H
	MOV	AX,0305H
	MOV	BX,0001H
	INT	16H
	INT	20H
CSEG	ENDS
	END	START