 1 Computer Associates Inter.   
 2 Borland International        
 3 Microsoft Corp.              
 4 Semantec Corp.               
 5 FUNCKY                       
 6 Софт-группа "МАК"            
 7 Central Point Software       
 8 Concentric Data Systems      
 9 Turbo Power Software         
10 Planet                       
11 BLINKER                      
12 American Cybernetics         
13 IBM Corp.                    