
|  The Thunderbyte Anti-Virus utilities provide a collection of sophisticated
  programs which offer various ways to check for, identify and remove known as
  well as unknown viruses from hard and floppy disks on PCs or across networks.

  TBAV is upgraded every two months. Free hotline support is provided for all
  registered users via telephone, fax and electronic bulletin board. Read the
  comprehensive documentation files for detailed information.
