{************************************************}
{                                                }
{   Turbo Pascal 6.0                             }
{   Turbo Vision Source Generator Demo           }
{   Copyright (c) 1992 by Phase Corporation      }
{                                                }
{************************************************}

{$X+,S-}
{$M 16384,8192,655360}

uses
  Dos, Objects, Drivers, Memory, Views, Menus, Dialogs, StdDlg, MsgBox, App;
const
  cmOpen = 100;
type

  { TDemoApplication }

  PDemoApplication = ^TDemoApplication;
  TDemoApplication = object(TApplication)
    constructor Init;
    procedure HandleEvent(var Event: TEvent); virtual;
    procedure InitMenuBar; virtual;
    procedure InitStatusLine; virtual;
  end;

{ TDemoApplication }
constructor TDemoApplication.Init;
var
  R: TRect;
  I: Integer;
  FileName: PathStr;
begin
  RegisterObjects;
  RegisterViews;
  RegisterMenus;
  RegisterDialogs;
  RegisterApp;

  TApplication.Init;

end;

procedure TDemoApplication.HandleEvent(var Event: TEvent);
{ This Find dialog procedure have been generated by TVGEN.
  The FIND.DLG object was given and FIND.INC was generated by Generate|Procedure
  command from TVGEN program.}
  
{$I find.inc}

var
    D   : PDialog;
    Rec : FindRec;
begin
  TApplication.HandleEvent(Event);
  case Event.What of
    evCommand:
      begin
        case Event.Command of
          cmOpen:
             begin
               Find(Rec);
             end;
        else
          Exit;
        end;
        ClearEvent(Event);
      end;
  end;
end;

{ This InitMenuBar procedure have been generated by TVGEN.
  The MENUBAR.MNU object was given and MENUBAR.INC file was created by 
  Generate|Procedure command from TVGEN program.}

{$I menuBar.inc}

{ This InitStatusLine procedure have been generated by TVGEN.
  The STATUS.STL object was given and STATUS.INC file was created by 
  Generate|Define Object command from TVGEN program.}
  
{$I Status.inc}

var
  Demo: TDemoApplication;
begin
  Demo.Init;
  Demo.Run;
  Demo.Done;
end.
