(***********************************************************************)

{ The minimal VCL's used string ID is 61440. The custom IDs must be
  less that above. }

const

  MaxExtStrID = 61400;

{ Component pages }

  srGadgets              = MaxExtStrID -  1;
  srDBExt                = MaxExtStrID -  2;

{ DBLists }

  SLocalDatabase         = MaxExtStrID -  3;

{ DualList }

  SDualListSrcCaption    = MaxExtStrID -  4;
  SDualListDestCaption   = MaxExtStrID -  5;

{ ServEdit }

  SBrowse                = MaxExtStrID -  6;
  SDefaultFilter         = MaxExtStrID -  7;

{ PickDate }

  SDateDlgTitle          = MaxExtStrID -  8;
  SNextYear              = MaxExtStrID -  9;
  SNextMonth             = MaxExtStrID - 10;
  SPrevYear              = MaxExtStrID - 11;
  SPrevMonth             = MaxExtStrID - 12;

{ VCLUtil }

  SNotImplemented        = MaxExtStrID - 13;
  SFileNotExec           = MaxExtStrID - 14;

{ DBTools }

  SRetryLogin            = MaxExtStrID - 15;

(************************************************************************)