# Whole file CRCs generated by Brik v1.0.  Use "brik -C" to verify them.

# CRC-32        filename
# ------        --------

2395754544      FILES
1324253258      flip.1
2015490080      flip.c
 116242883      flip.h
3654056916      flip.man
3390294771      flip.prj
2215166699      getopt.c
3196976162      install.doc
3441461244      makefile.nix
2236661872      makefile.tcc
3460687634      turboc.c
1182134946      turboc.cfg
